### ISSUE TITLE
Android API 30 ShareMenuModule.getSharedText crashing app. java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by raveracker** [Expensify/react-native-share-menu#104]
On Android SDK API 30 the app crashes on Firebase test lab Pixel 4 on listener being called.

Deep dive into the code. I found out that 

```
react-native-share-menu/android/src/main/java/com/meedan/ShareMenuModule.java:92: warning: non-varargs call of varargs method with inexact argument type for last parameter;
      successCallback.invoke(null);
```

I commented out line 92 in the file and tested the same and the functionality is working. Let me know if there are anything that would miss out if it is commented out.

**Comment by lukebrandonfarrell** [comment]
@raveracker There isn't any issue with NOT firing the callback, could you make a PR?

**Comment by raveracker** [comment]
This was the native error in API 30. I don't know how to make a PR. :sweat_smile:

```
at com.meedan.ShareMenuModule.getSharedText(Unknown Source:7)
     FATAL EXCEPTION: mqt_native_modules
Process: com.docmydoc, PID: 27091
java.lang.NullPointerException: Attempt to get length of null array
	at com.facebook.react.bridge.Arguments.fromJavaArgs(Unknown Source:6)
	at com.facebook.react.bridge.CallbackImpl.invoke(Unknown Source:8)
	at com.meedan.ShareMenuModule.getSharedText(Unknown Source:7)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:147)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by lukebrandonfarrell** [comment]
Yeah you were right, you want to remove the `successCallback.invoke(null)` and now is a great time to learn https://opensource.com/article/19/7/create-pull-request-github :)

**Comment by jayeshkarma100** [comment]
i have resolved this problem by putting a condition on intent.gettype() in  ShareMenuModule.java file like this 

    String type = null;
if(intent.getType()!=null){ type = intent.getType(); }
    if (type == null) { return null; }
    
    it's because of Hot reloading in RN 
    I hope this will be helpful for you , if yes please Like it

**Comment by HugoGresse** [comment]
@caiosba could you take a look at this issue and the linked PR? this result in a lot of crashed at app start.

**Comment by caiosba** [comment]
Done, thanks
