### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by vbashiri** [Expensify/react-native-share-menu#36]
Try to build the example project and got this error at the very first step `npm install`. Seems to be a problem with the "nan" module.
`./node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);`
node version: v11.2.0

complete log:

```
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated joi@6.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated topo@1.1.0: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam

> bufferutil@1.2.1 install /Users/vahidbashiri/Work/react-native-share-menu/example/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.cc:49:40: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> bufferObj = info[0]->ToObject();
                                       ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:56:42: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
      Local<Object> src = array->Get(i)->ToObject();
                                         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:67:41: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> buffer_obj = info[0]->ToObject();
                                        ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:69:39: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> mask_obj = info[1]->ToObject();
                                      ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:88:41: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> buffer_obj = info[0]->ToObject();
                                        ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:89:39: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> mask_obj = info[1]->ToObject();
                                      ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:91:41: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> output_obj = info[2]->ToObject();
                                        ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:92:40: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
    unsigned int dataOffset = info[3]->Int32Value();
                                       ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/bufferutil.cc:93:36: warning: 'Int32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
    unsigned int length = info[4]->Int32Value();
                                   ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2572:3: note: 'Int32Value' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
9 warnings generated.
  SOLINK_MODULE(target) Release/bufferutil.node

> fsevents@1.2.7 install /Users/vahidbashiri/Work/react-native-share-menu/example/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
[fsevents] Success: "/Users/vahidbashiri/Work/react-native-share-menu/example/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> utf-8-validate@1.2.2 install /Users/vahidbashiri/Work/react-native-share-menu/example/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
In file included from ../node_modules/nan/nan.h:190:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/validation.cc:15:
In file included from ../node_modules/nan/nan.h:196:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:345:28: warning: 'New' is deprecated: Use Isolate* version
      [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:5241:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:844:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:890:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:900:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated
      here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:1447:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
      [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/validation.cc:131:41: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<Object> buffer_obj = info[0]->ToObject();
                                        ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated
      here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/vahidbashiri/.node-gyp/11.2.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
8 warnings and 1 error generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vahidbashiri/Work/react-native-share-menu/example/node_modules/utf-8-validate
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> spawn-sync@1.0.15 postinstall /Users/vahidbashiri/Work/react-native-share-menu/example/node_modules/spawn-sync
> node postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1030 packages from 684 contributors and audited 5321 packages in 33.775s
found 46 vulnerabilities (23 low, 13 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by caiosba** [comment]
Can you please try what is suggested at https://github.com/nodejs/nan/issues/763?

**Comment by caiosba** [comment]
Seems to be an issue with Nan module, not React Native Share Menu.

**Comment by vbashiri** [comment]
I fixed that with `npm audit fix`
and then build gradle following [this instruction.](https://stackoverflow.com/questions/44546849/unsupported-method-baseconfig-getapplicationidsuffix#answer-44547225)
now I have this issue #34.
react-native version is 0.58.6

 note that react-native-share-menu works in my project but doesn't receive when the app is already open (same as #18) and I want to see if the problem is from my code and where is the problem.

**Comment by caiosba** [comment]
Ok, I'll check with React Native 0.58.6.

**Comment by caiosba** [comment]
Please try with the latest version of this module (2.2.1), which contains a fix for that.

**Comment by vbashiri** [comment]
tried new version (2.2.2)
It throws this error >>

.../react-native-share-menu/example/node_modules/react-native-share-menu/android/src/main/java/com/meedan/ShareMenuPackage.java:16: error: ShareMenuPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class ShareMenuPackage implements ReactPackage {
...........^
